# /frontend/netlify.toml

[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"
  functions = "netlify/functions"
  

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200