[build]
  command = "cd frontend && npm run build"  
  publish = "frontend/dist"  
   

[dev]
  framework = "vite"  
  port = 3000  
  autoLaunch = false 

[functions] 
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200